from flask import request, jsonify, make_response
from flask.views import MethodView
from flask_smorest import Blueprint
from app.controllers.attendance_controller import AttendanceController

attendance_blueprint = Blueprint('api', 'api', url_prefix="/api",
                                 description="The general blueprint" )

@attendance_blueprint.route("/")
class AttendanceCollection(MethodView):
    """
    Represents the collection of Attendance resources.

    This class handles the operations related to the Attendance API, such as
    defining routes for handling specific HTTP methods at the root level.

    """
    @attendance_blueprint.response(200)
    def get(self):
        """
        Handles GET request to the endpoint

        :return: A JSON response with a message
        """
        return {'message': 'Attendance API'}

@attendance_blueprint.route('/attendance', methods=['POST'])
def create_attendance():
    """
    Handles the creation of attendance records through a POST endpoint. This function
    acts as the route handler for the specified endpoint and delegates the processing
    of the provided data to the associated controller.

    :param request: The HTTP request containing the JSON payload for the attendance
                    record in its body.
    :type request: flask.Request

    :return: The response generated by the AttendanceController after processing the
             provided attendance data.
    :rtype: flask.Response
    """
    return AttendanceController.create_attendance(request.json)
