services:
  kpi-database:
    image: postgres:13
    container_name: kpi-database
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: kpi-api-database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app_network
  kpi-automation-api:
    container_name: kpi-automation-apis
    image: kpi-automation-api:latest
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
#    depends_on:
#          - kpi-database
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres-data:
